#!/bin/bash
set -e

REGISTRY=dockerreg.chtc.wisc.edu

TAG=opensciencegrid/koji-builder:fresh

docker build -t $TAG .
docker tag $TAG $REGISTRY/$TAG
docker push $REGISTRY/$TAG
docker rmi $REGISTRY/$TAG
